import type { Metadata } from "next";
import './globals.css'
import { AppProvider } from "./context/context";
import { Space_Grotesk } from 'next/font/google'


export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
   icons: {
    icon: [
      { url: '/pokeball.webp' },
      { url: '/pokeball.webp', type: 'image/png' },
    ],
    apple: [
      { url: '/pokeballPNG.png' },
    ],
  }
};

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500','600', '700'], 
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceGrotesk.className}>
      <body >
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
